import { mkdir } from "node:fs/promises";
import { SCHEMA_VERSION } from "./schema.js";
import type { Graph, Manifest } from "./schema.js";
import { DataQualityLog } from "./data-quality.js";
import { composeGraph } from "./build/graph.js";
import { nowIso, path, readJson, writeJson, writeText } from "./util.js";

const PIPELINE_VERSION = "0.0.1";

const LAG_ORDER: Record<string, number> = {
  behind_major: 0,
  behind_minor: 1,
  unknown: 2,
  up_to_date: 3,
};

/**
 * Release management: given a core library node id, list everything that
 * depends on it, most-at-risk first. This is the second purpose of nutgraph --
 * "what do we test before the next breaking release?"
 */
async function impact(nodeId: string): Promise<void> {
  const graph = await readJson<Graph>(path("dist", "graph.json"));
  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  const target = byId.get(nodeId);
  if (!target) {
    console.error(`No such node: ${nodeId}`);
    process.exit(1);
  }
  const deps = graph.edges
    .filter((e) => e.type === "depends_on" && e.to === nodeId)
    .sort((a, b) => (LAG_ORDER[a.lag ?? "unknown"] ?? 9) - (LAG_ORDER[b.lag ?? "unknown"] ?? 9));

  console.log(`Impact of ${nodeId} (${target.name}) -- ${deps.length} dependent(s)\n`);
  const fmt = (e: (typeof deps)[number]) => {
    const n = byId.get(e.from);
    const stale = n?.metrics?.last_commit
      ? `${Math.round((Date.now() - Date.parse(n.metrics.last_commit)) / 86_400_000)}d`
      : "?";
    return `  [${(e.lag ?? "unknown").padEnd(12)}] ${e.from.padEnd(38)} ${(e.declared_range ?? "?").padEnd(14)} -> ${(e.latest_at_build ?? "?").padEnd(10)} last commit ${stale}`;
  };
  for (const e of deps) console.log(fmt(e));
}

const SCHEMA_DOC = `# nutgraph data schema v${SCHEMA_VERSION}

Generated by \`nutgraph build\`. This is the contract for downstream consumers
(the site, release tooling, and agents).

## Files

- \`graph.json\` -- the full graph (nodes + edges + counts).
- \`nodes.jsonl\` -- one node per line (streaming / large-graph consumers).
- \`edges.jsonl\` -- one edge per line.
- \`manifest.json\` -- schema version, build time, counts, data-quality count.

## Node types

spec, nut, core_lib, binding, library, mint_software, mint_instance, wallet, app, tool, org.

## Edge types

- \`depends_on\` -- project -> core_lib (versioned, machine-derived; M1)
- \`imports\` -- project -> library (heuristic, unversioned)
- \`binding_of\` -- binding -> core_lib
- \`fork_of\` -- project -> project
- \`implements\` -- lib/mint -> nut (compatibility matrix)
- \`runs\` -- mint_instance -> mint_software
- \`maintained_by\` -- project -> org

## Provenance

Every node/edge carries \`sources[]\` (\`kind\`, \`ref\`, \`url\`) and, for edges,
a \`confidence\` in 0..1. Data quality issues are rendered to \`DATA_QUALITY.md\`.
`;

async function writeOutputs(graph: Graph, dq: DataQualityLog): Promise<void> {
  const dist = path("dist");
  await mkdir(dist, { recursive: true });

  await writeJson(path("dist", "graph.json"), graph);
  await writeText(
    path("dist", "nodes.jsonl"),
    graph.nodes.map((n) => JSON.stringify(n)).join("\n") + "\n",
  );
  await writeText(
    path("dist", "edges.jsonl"),
    graph.edges.map((e) => JSON.stringify(e)).join("\n") + "\n",
  );
  await writeText(path("dist", "schema.md"), SCHEMA_DOC);

  const manifest: Manifest = {
    schema_version: SCHEMA_VERSION,
    generated_at: graph.generated_at,
    pipeline_version: PIPELINE_VERSION,
    counts: graph.counts,
    data_quality_issues: dq.count,
  };
  await writeJson(path("dist", "manifest.json"), manifest);

  await writeText(path("DATA_QUALITY.md"), dq.renderMarkdown(graph.generated_at));

  // Dated snapshot for growth animation + release diffs.
  const day = graph.generated_at.slice(0, 10);
  await writeJson(path("snapshots", `${day}.json`), graph);

  // The static site (M4) loads ./graph.json from its own directory so it can be
  // deployed independently (GitHub Pages).
  await writeJson(path("site", "graph.json"), graph);
}

function summarize(graph: Graph, dq: DataQualityLog): string {
  const lines: string[] = [];
  lines.push(`nodes: ${graph.counts.nodes}  edges: ${graph.counts.edges}`);
  const types = Object.entries(graph.counts.by_type).sort((a, b) => b[1] - a[1]);
  lines.push("by type: " + types.map(([t, c]) => `${t}=${c}`).join(" "));
  const edgeTypes = graph.edges.reduce<Record<string, number>>((acc, e) => {
    acc[e.type] = (acc[e.type] ?? 0) + 1;
    return acc;
  }, {});
  lines.push(
    "by edge: " +
      Object.entries(edgeTypes)
        .sort((a, b) => b[1] - a[1])
        .map(([t, c]) => `${t}=${c}`)
        .join(" "),
  );
  const sev = dq.bySeverity();
  lines.push(`data quality: ${dq.count} (${sev.error} error, ${sev.warn} warn, ${sev.info} info)`);
  return lines.join("\n");
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const cmd = args[0] ?? "build";
  const refresh = args.includes("--refresh");

  if (cmd === "build" || cmd === "graph" || cmd === "readme") {
    const dq = new DataQualityLog();
    const graph = await composeGraph(dq, refresh);
    if (cmd === "build") {
      await writeOutputs(graph, dq);
      console.log("nutgraph build complete.");
    }
    console.log(summarize(graph, dq));
    return;
  }

  if (cmd === "impact") {
    const id = args.find((a) => !a.startsWith("--") && a !== "impact");
    if (!id) {
      console.error("usage: nutgraph impact <nodeId>");
      process.exit(1);
    }
    await impact(id);
    return;
  }

  console.error(
    `unknown command: ${cmd}\nusage: nutgraph [build|graph|readme|impact <nodeId>] [--refresh]`,
  );
  process.exit(1);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
