/**
 * Data-quality ledger.
 *
 * Every stage can record an issue here instead of silently dropping or guessing
 * at bad data. `nutgraph build` renders this to DATA_QUALITY.md and reports the
 * count in the agent manifest, so problems are visible and fixable rather than
 * buried in logs.
 */

export type Severity = "error" | "warn" | "info";

export interface DqIssue {
  code: string;
  severity: Severity;
  subject: string;
  detail: string;
  suggestion?: string;
}

const CODE_DOCS: Record<string, string> = {
  README_PARSE_NO_URL: "A README list item had no parseable URL and was skipped.",
  README_TYPE_INFERRED:
    "Node type was inferred from the README section and may be wrong; add an override in ontology/projects.yaml.",
  README_DUPLICATE_ID:
    "Two README entries resolved to the same canonical id; they were merged. Verify the merge is correct.",
  README_NO_REPO:
    "A listed project has no GitHub/Forgejo repo, so its dependencies cannot be derived. It will never have edges until a repo or override is supplied.",
  NODE_UNRESOLVED_PARENT:
    "primary_parent points at a node id that does not exist in the ontology.",
  CORE_NOT_IN_README:
    "A curated core/binding node was not found in the awesome-cashu README; the list may have moved or renamed it.",
  NUTS_FETCH_FAILED:
    "Could not fetch the live NUT list from cashubtc/nuts; fell back to the curated seed. NUT nodes may be stale.",
  NUTS_FALLBACK_USED: "NUT nodes came from the curated seed rather than the live spec repo.",
  FETCH_FAILED: "A required network resource could not be fetched (cached copy may be used).",
  NUT_IMPLEMENTER_UNMATCHED:
    "The spec README credits a wallet/mint with a NUT, but no matching node exists (or it is not in the list). Add it to the ontology or accept the missing edge.",
  PACKAGE_TARGET_MISSING:
    "A machine-read dependency maps (via ontology/packages.yaml) to a node that is not in the graph. Add the project or fix the mapping.",
  DEP_NO_MANIFEST:
    "No parseable dependency manifest was found for an open-source project, so it has no depends_on edges.",
  METADATA_MISSING:
    "Repo metadata could not be fetched (e.g. transient GitHub 502 or missing repo). Metrics/ranking will be absent until a later run fills the cache.",
  AUTH_STATUS: "Which GitHub identity the run authenticated as, and remaining API budget (informational).",
  AUTH_REJECTED:
    "A token is set but GitHub rejected it -- usually a fine-grained PAT that does not cover these repositories, or missing scopes.",
  UNAUTHENTICATED: "No GitHub token; API access is heavily rate-limited (60/hour).",
  MINT_SOFTWARE_UNKNOWN:
    "A live mint did not report which software it runs, so no `runs` edge was created. Implementation detection is weak by design.",
  NOSTR_UNAVAILABLE:
    "NIP-87 relays could not be queried (likely network restrictions). Seed/directory sources still apply.",
  DIRECTORY_UNREACHABLE: "A mint directory page could not be fetched.",
  MINT_DISCOVERY_SUMMARY: "Summary of mint discovery for the run (informational).",
  MANAGER_UNSUPPORTED:
    "A dependency's package manager has no registry adapter yet, so its version cannot be tracked.",
  ONTOLOGY_NODE_MISSING:
    "A curated core/binding references a parent or repo that could not be resolved.",
  AMBIGUOUS_TYPE: "Node type could not be determined confidently.",
};

export class DataQualityLog {
  private issues: DqIssue[] = [];

  add(issue: DqIssue): void {
    this.issues.push(issue);
  }

  get all(): readonly DqIssue[] {
    return this.issues;
  }

  get count(): number {
    return this.issues.length;
  }

  bySeverity(): Record<Severity, number> {
    return this.issues.reduce(
      (acc, i) => ((acc[i.severity] = (acc[i.severity] ?? 0) + 1), acc),
      { error: 0, warn: 0, info: 0 } as Record<Severity, number>,
    );
  }

  renderMarkdown(generatedAt: string): string {
    const counts = this.bySeverity();
    const lines: string[] = [];
    lines.push("# Data quality ledger");
    lines.push("");
    lines.push(
      "Auto-generated by `nutgraph build`. Do not edit by hand -- fix the underlying",
    );
    lines.push("data or add an override, then rebuild.");
    lines.push("");
    lines.push(`Generated: ${generatedAt}`);
    lines.push("");
    lines.push(
      `**${this.issues.length} issue(s)** -- ${counts.error} error, ${counts.warn} warn, ${counts.info} info.`,
    );
    lines.push("");

    const codes = [...new Set(this.issues.map((i) => i.code))].sort();
    for (const code of codes) {
      const group = this.issues.filter((i) => i.code === code);
      lines.push(`## ${code} (${group.length})`);
      lines.push("");
      if (CODE_DOCS[code]) {
        lines.push(`> ${CODE_DOCS[code]}`);
        lines.push("");
      }
      lines.push("| severity | subject | detail | suggestion |");
      lines.push("| --- | --- | --- | --- |");
      for (const i of group) {
        lines.push(
          `| ${i.severity} | ${esc(i.subject)} | ${esc(i.detail)} | ${esc(i.suggestion ?? "")} |`,
        );
      }
      lines.push("");
    }

    if (this.issues.length === 0) {
      lines.push("No issues recorded.");
      lines.push("");
    }
    return lines.join("\n");
  }
}

function esc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}
